CREATE TABLE AG_GRAFICO (
     CODIGO BIGINT(20) NOT NULL AUTO_INCREMENT,
     DESCRICAO VARCHAR(50) NOT NULL,
     TIPO INTEGER,
     ANEXO VARCHAR(200),
	 CODIGO_USUARIO BIGINT(20) NOT NULL,
     PRIMARY KEY (CODIGO)
);

ALTER TABLE AG_GRAFICO ADD CONSTRAINT FK_USUARIO_GRAFICO FOREIGN KEY (CODIGO_USUARIO) REFERENCES AG_USUARIO_PORTAL (CODIGO);

SELECT * FROM  AG_GRAFICO;