CREATE TABLE AG_PERMISSOES (
     CODIGO BIGINT(20) NOT NULL AUTO_INCREMENT,
     CODIGO_USUARIO BIGINT(20) NOT NULL,
     PERM_ALTERACAO VARCHAR(60) NOT NULL,
     PERM_EXCLUSAO VARCHAR(60) NOT NULL,
     PERM_GRAFICO VARCHAR(60) NOT NULL,
     PERM_INCLUIR VARCHAR(60) NOT NULL,
     PERM_VISUALIZAR_LOGIN VARCHAR(60) NOT NULL,
     PRIMARY KEY (CODIGO)
);

ALTER TABLE AG_PERMISSOES ADD CONSTRAINT FK_USUARIO FOREIGN KEY (CODIGO_USUARIO) REFERENCES AG_USUARIO_PORTAL (CODIGO);

INSERT INTO AG_PERMISSOES (CODIGO, CODIGO_USUARIO, PERM_ALTERACAO, PERM_EXCLUSAO, PERM_GRAFICO, PERM_INCLUIR, PERM_VISUALIZAR_LOGIN)
VALUES (1, 1, 'S', 'S', 'S', 'S', 'S');

SELECT * FROM AG_PERMISSOES;