SELECT * FROM AG_PERMISSOES
WHERE CODIGO_USUARIO = 1;

SELECT USU.CODIGO,
	   USU.NOME,
       USU.EMAIL,
       USU.SENHA,
       USU.CPF,
       USU.MATRICULA,
       USU.LOGIN,
       USU.DATA_CADASTRO,
       CASE USU.STATUS
			WHEN  'A'  then 'ATIVO'
            WHEN  'B' then 'BLOQUEADO'
            WHEN  'C' then 'CANCELADO'
	   END AS DESCRICAO_STATUS,
       PER.PERM_ALTERACAO ALTERAR,
       PER.PERM_EXCLUSAO EXCLUIR,
       PER.PERM_GRAFICO IMPRIMIR,
	   PER.PERM_INCLUIR INCLUIR,
	   PER.PERM_VISUALIZAR_LOGIN VISUALIZAR_LOGINS
FROM AG_USUARIO_PORTAL USU,
	 AG_PERMISSOES PER
WHERE USU.CODIGO = PER.CODIGO
AND UPPER(USU.STATUS_USUARIO) = 'A'
