CREATE TABLE AG_USUARIO_PORTAL (
     CODIGO BIGINT(20) NOT NULL AUTO_INCREMENT,
     NOME VARCHAR(100) NOT NULL,
     EMAIL VARCHAR(70) NOT NULL,
     CPF VARCHAR(11) NOT NULL,
     MATRICULA VARCHAR(10) NOT NULL,
     SENHA VARCHAR(12) NOT NULL,
     LOGIN VARCHAR(30) NOT NULL,
     DATA_CADASTRO DATE,
     STATUS VARCHAR(1) NOT NULL,
     PRIMARY KEY (CODIGO)
);

DELIMITER $
CREATE TRIGGER `AG_DATA_CADASTRO` BEFORE UPDATE ON `AG_USUARIO_PORTAL`
 FOR EACH ROW SET NEW.DATA_CADASTRO = NOW()
DELIMITER ;



ALTER TABLE AG_USUARIO_PORTAL ADD CONSTRAINT UN_CPF UNIQUE (CPF);

INSERT INTO AG_USUARIO_PORTAL (NOME, EMAIL, CPF, MATRICULA, SENHA, LOGIN)
VALUES ('Administrador', 'agrodados@gmail.com', '00000000191','12345','12345', 'admin');

SELECT * FROM AG_USUARIO_PORTAL;

ALTER TABLE AG_USUARIO_PORTAL ADD STATUS DEFAULT 'A';

ALTER TABLE AG_USUARIO_PORTAL CHANGE `STATUS` `STATUS` VARCHAR(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'A';