CREATE DATABASE agrodados;

USE agrodados;


CREATE TABLE AG_USUARIO_PORTAL (
     CODIGO BIGINT(20) NOT NULL AUTO_INCREMENT,
     NOME VARCHAR(100) NOT NULL,
     EMAIL VARCHAR(70) NOT NULL,
     CPF VARCHAR(11) NOT NULL,
     MATRICULA VARCHAR(10) NOT NULL,
     SENHA VARCHAR(12) NOT NULL,
     LOGIN VARCHAR(30) NOT NULL,
     DATA_CADASTRO DATE,
     STATUS VARCHAR(1) NOT NULL,
     PRIMARY KEY (CODIGO)
);

INSERT INTO AG_USUARIO_PORTAL (CODIGO, NOME, EMAIL, CPF, MATRICULA, SENHA, LOGIN, DATA_CADASTRO, STATUS)
VALUES (1, 'Administrador', 'agrodados@gmail.com', '00000000191','12345','12345', 'admin', '2020-07-19', 'A');



CREATE TABLE AG_PERMISSOES (
     CODIGO BIGINT(20) NOT NULL AUTO_INCREMENT,
     CODIGO_USUARIO BIGINT(20) NOT NULL,
     PERM_ALTERACAO VARCHAR(60) NOT NULL,
     PERM_EXCLUSAO VARCHAR(60) NOT NULL,
     PERM_GRAFICO VARCHAR(60) NOT NULL,
     PERM_INCLUIR VARCHAR(60) NOT NULL,
     PERM_VISUALIZAR_LOGIN VARCHAR(60) NOT NULL,
     PRIMARY KEY (CODIGO)
);


ALTER TABLE AG_PERMISSOES ADD CONSTRAINT FK_USUARIO FOREIGN KEY (CODIGO_USUARIO) REFERENCES AG_USUARIO_PORTAL (CODIGO);

CREATE TABLE AG_GRAFICO (
     CODIGO BIGINT(20) NOT NULL AUTO_INCREMENT,
     DESCRICAO VARCHAR(50) NOT NULL,
     TIPO INTEGER,
     PRIMARY KEY (CODIGO)
);

INSERT INTO AG_PERMISSOES (CODIGO, CODIGO_USUARIO, PERM_ALTERACAO, PERM_EXCLUSAO, PERM_IMPRESSAO, PERM_INCLUIR, PERM_VISUALIZAR_LOGIN)
VALUES (1, 1, 'S', 'S', 'S', 'S', 'S');


SELECT * FROM AG_PERMISSOES
WHERE CODIGO_USUARIO = 1;

SELECT USU.CODIGO,
	   USU.NOME,
       USU.EMAIL,
       USU.SENHA,
       USU.CPF,
       USU.MATRICULA,
       USU.LOGIN,
       USU.DATA_CADASTRO,
       CASE USU.STATUS
			WHEN  'A'  then 'ATIVO'
            WHEN  'B' then 'BLOQUEADO'
            WHEN  'C' then 'CANCELADO'
	   END AS DESCRICAO_STATUS,
       PER.PERM_ALTERACAO ALTERAR,
       PER.PERM_EXCLUSAO EXCLUIR,
       PER.PERM_GRAFICO IMPRIMIR,
	   PER.PERM_INCLUIR INCLUIR,
	   PER.PERM_VISUALIZAR_LOGIN VISUALIZAR_LOGINS
FROM AG_USUARIO_PORTAL USU,
	 AG_PERMISSOES PER
WHERE USU.CODIGO = PER.CODIGO
AND UPPER(USU.STATUS_USUARIO) = 'A'
